<script src="{{ public_asset('js/insul/assets/js/libs/jquery.magnific-popup.min.js?ver=1.0.4') }}" id="magnific-popup-js"></script>
<script defer src="{{ public_asset('js/mailchimp/assets/js/forms.js?ver=4.9.19') }}" id="mc4wp-forms-api-js"></script>
<script src="{{ public_asset('js/elementor/assets/js/webpack.runtime.min.js?ver=3.25.11') }}" id="elementor-webpack-runtime-js"></script>
<script src="{{ public_asset('js/elementor/assets/js/frontend-modules.min.js?ver=3.25.11') }}" id="elementor-frontend-modules-js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-ui@1.13.3/dist/jquery-ui.min.js" id="jquery-ui-core-js"></script>
<script id="elementor-frontend-js-before">
var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":false},"i18n":{"shareOnFacebook":"Share on Facebook","shareOnTwitter":"Share on Twitter","pinIt":"Pin it","download":"Download","downloadImage":"Download image","fullscreen":"Fullscreen","zoom":"Zoom","share":"Share","playVideo":"Play Video","previous":"Previous","next":"Next","close":"Close","a11yCarouselWrapperAriaLabel":"Carousel | Horizontal scrolling: Arrow Left & Right","a11yCarouselPrevSlideMessage":"Previous slide","a11yCarouselNextSlideMessage":"Next slide","a11yCarouselFirstSlideMessage":"This is the first slide","a11yCarouselLastSlideMessage":"This is the last slide","a11yCarouselPaginationBulletMessage":"Go to slide"},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"responsive":{"breakpoints":{"mobile":{"label":"Mobile Portrait","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobile Landscape","value":880,"default_value":880,"direction":"max","is_enabled":true},"tablet":{"label":"Tablet Portrait","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet Landscape","value":1200,"default_value":1200,"direction":"max","is_enabled":true},"laptop":{"label":"Laptop","value":1440,"default_value":1366,"direction":"max","is_enabled":true},"widescreen":{"label":"Widescreen","value":2400,"default_value":2400,"direction":"min","is_enabled":false}},"hasCustomBreakpoints":true},"version":"3.25.11","is_static":false,"experimentalFeatures":{"additional_custom_breakpoints":true,"container":true,"e_swiper_latest":true,"e_nested_atomic_repeaters":true,"e_optimized_control_loading":true,"e_onboarding":true,"e_css_smooth_scroll":true,"home_screen":true,"landing-pages":true,"nested-elements":true,"editor_v2":true,"link-in-bio":true,"floating-buttons":true},"urls":{"assets":"\/wp-content\/plugins\/elementor\/assets\/","ajaxurl":"\/wp-admin\/admin-ajax.php","uploadUrl":"\/wp-content\/uploads"},"nonces":{"floatingButtonsClickTracking":"2418f30110"},"swiperClass":"swiper","settings":{"page":[],"editorPreferences":[]},"kit":{"active_breakpoints":["viewport_mobile","viewport_mobile_extra","viewport_tablet","viewport_tablet_extra","viewport_laptop"],"body_background_background":"classic","viewport_laptop":1440,"global_image_lightbox":"yes","lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description"},"post":{"id":127,"title":"FAQs%20Page%20%E2%80%93%20Insul","excerpt":"","featuredImage":false}};
</script>
<script src="{{ public_asset('js/elementor/assets/js/frontend.min.js?ver=3.25.11') }}" id="elementor-frontend-js"></script>
<script src="{{ public_asset('js/insul/assets/js/elementor/accordion.js?ver=1.0.4') }}" id="insul-elementor-accordion-js"></script>
<script src="{{ public_asset('js/insul/assets/js/elementor/animated-headline.js?ver=1.0.4') }}" id="insul-elementor-animated-headline-js"></script>
<script src="{{ public_asset('js/insul/assets/js/elementor/image-carousel.js?ver=1.0.4') }}" id="insul-elementor-image-carousel-js"></script>
<script src="{{ public_asset('js/insul/assets/js/elementor/slider-scrolling.js?ver=1.0.4') }}" id="insul-elementor-slider-scrolling-js"></script>
<script src="{{ public_asset('js/insul/assets/js/elementor-frontend.js?ver=1.0.4') }}" id="insul-elementor-frontend-js"></script>
<script src="{{ public_asset('js/insul/assets/js/frontend/jquery-sticky.js?ver=1.0.4') }}" id="elementor-sticky-js"></script>
<script src="{{ public_asset('js/insul/assets/js/libs/sticky.js?ver=1.0.4') }}" id="insul-elementor-sticky-js"></script>
</body>
</html>
