<?php

return [
    'initial_delay_ms' => 0,
    'interval_min_ms' => 20000,
    'interval_max_ms' => 45000,

    'whatsapp' => [
        'number' => '919711043285',
        'default_message' => 'Hi, I would like to know more about your insurance services.',
    ],

    'small_variants' => [
        [
            'id' => 'wa-instant-reply',
            'fomo' => 'Usually replies in minutes',
            'title' => 'Questions? Chat on WhatsApp',
            'text' => 'Skip the wait — message our team now for quick answers on insurance & investments.',
            'whatsapp_message' => 'Hi, I have a quick question about your services.',
            'submit' => 'Chat on WhatsApp',
        ],
        [
            'id' => 'wa-sip-help',
            'fomo' => 'SIP experts online now',
            'title' => 'Start your SIP via WhatsApp',
            'text' => 'Tell us your budget — we\'ll suggest a plan in one chat. No forms needed.',
            'whatsapp_message' => 'Hi, I want help starting a SIP plan.',
            'submit' => 'Message on WhatsApp',
        ],
        [
            'id' => 'wa-quote-fast',
            'fomo' => 'Get a quote in one chat',
            'title' => 'Need a quote today?',
            'text' => 'Life or general insurance — share basics on WhatsApp and we\'ll respond fast.',
            'whatsapp_message' => 'Hi, I need an insurance quote.',
            'submit' => 'Get Quote on WhatsApp',
        ],
        [
            'id' => 'wa-portfolio',
            'fomo' => 'Limited advisor slots',
            'title' => 'Free portfolio chat',
            'text' => 'Act before the week ends — tap below to book a quick WhatsApp review.',
            'whatsapp_message' => 'Hi, I\'d like a portfolio review on WhatsApp.',
            'submit' => 'Book on WhatsApp',
        ],
        [
            'id' => 'wa-renewal',
            'fomo' => 'Renewal deadline coming up?',
            'title' => 'Renewal help on WhatsApp',
            'text' => 'Don\'t overpay — message us your policy type and we\'ll compare options for you.',
            'whatsapp_message' => 'Hi, I need help with policy renewal.',
            'submit' => 'Chat Now',
        ],
    ],

    'big_variants' => [
        [
            'id' => 'free-consultation',
            'eyebrow' => 'Limited availability',
            'fomo' => 'Only 4 callback slots left today',
            'title' => 'Claim your free financial consultation',
            'text' => 'Advisors are filling up fast this week. Reserve your spot now — no obligation, personalised guidance for your goals.',
            'subject' => 'CTA Popup – Free Consultation (FOMO)',
            'submit' => 'Reserve My Slot',
        ],
        [
            'id' => 'portfolio-review',
            'eyebrow' => 'This week only',
            'fomo' => 'Offer ends Sunday — 12 reviews booked',
            'title' => 'Get a complimentary portfolio review',
            'text' => 'Most clients wait months for this. We\'re opening a short window for a no-cost review of your insurance and investments.',
            'subject' => 'CTA Popup – Portfolio Review (FOMO)',
            'submit' => 'Book Free Review',
        ],
        [
            'id' => 'sip-planner',
            'eyebrow' => 'Don\'t delay your SIP',
            'fomo' => 'Every month you wait costs more',
            'title' => 'Start your SIP plan before rates move',
            'text' => 'Delaying even one month can cost lakhs over time. Talk to an advisor today and lock in a plan that fits your budget.',
            'subject' => 'CTA Popup – SIP Planning (FOMO)',
            'submit' => 'Plan My SIP Now',
        ],
        [
            'id' => 'life-insurance',
            'eyebrow' => 'Rates won\'t stay low',
            'fomo' => 'Premium revisions expected soon',
            'title' => 'Secure life cover at today\'s rates',
            'text' => 'Families who act early save more. Get a tailored life insurance quote while current premiums are still available.',
            'subject' => 'CTA Popup – Life Insurance (FOMO)',
            'submit' => 'Get My Quote',
        ],
        [
            'id' => 'general-insurance',
            'eyebrow' => 'Renewal season',
            'fomo' => 'Compare plans in under 24 hours',
            'title' => 'Don\'t overpay on your next renewal',
            'text' => 'Others are switching and saving. Share your details — we\'ll find better health, motor, or home cover before your policy lapses.',
            'subject' => 'CTA Popup – General Insurance (FOMO)',
            'submit' => 'Compare & Save',
        ],
        [
            'id' => 'mutual-funds',
            'eyebrow' => 'Markets won\'t wait',
            'fomo' => 'Join 200+ investors guided this month',
            'title' => 'Miss the rally or start investing smart?',
            'text' => 'Waiting on the sidelines is the costliest mistake. Get expert mutual fund guidance aligned to your risk profile — free callback.',
            'subject' => 'CTA Popup – Mutual Funds (FOMO)',
            'submit' => 'Start Investing Smart',
        ],
        [
            'id' => 'callback-urgent',
            'eyebrow' => 'Act now',
            'fomo' => 'Response within 2 hours — today only',
            'title' => 'Your advisor callback is one form away',
            'text' => 'Hundreds visited this site today. Priority callbacks are limited — submit now and we\'ll reach you before end of business.',
            'subject' => 'CTA Popup – Priority Callback (FOMO)',
            'submit' => 'Get Priority Callback',
        ],
    ],
];
